package com.italia.marxmind.bris.enm;

public enum KPForms {
	
	KP_FORM0(0,"RECEIPT FORM"),
	KP_FORM1(1,"KP FORM # 1: NOTICE TO CONSTITUTE THE LUPON"),
	KP_FORM2(2,"KP FORM # 2: APPOINTMENT LETTER"),
	KP_FORM3(3,"KP FORM # 3: NOTICE OF APPOINTMENT"),
	KP_FORM4(4,"KP FORM # 4: LIST OF APPOINTED LUPON MEMBERS"),
	KP_FORM5(5,"KP FORM # 5: LUPON MEMBER OATH STATEMENT"),
	KP_FORM6(6,"KP FORM # 6: WITHDRAWAL OF APPOINTMENT"),
	KP_FORM7(7,"KP FORM # 7: COMPLAINANT’S FORM"),
	KP_FORM8(8,"KP FORM # 8: NOTICE OF HEARING (MEDIATION PROCEEDINGS)"),
	KP_FORM9(9,"KP FORM # 9: SUMMON FOR THE RESPONDENT"),
	KP_FORM10(10,"KP FORM # 10: NOTICE FOR CONSTITUTION OF PANGKAT"),
	KP_FORM11(11,"KP FORM # 11: NOTICE TO CHOSEN PANGKAT MEMBER"),
	KP_FORM12(12,"KP FORM # 12: NOTICE OF HEARING (CONCILIATION PROCEEDINGS)"),
	KP_FORM13(13,"KP FORM # 13: SUBPOENA LETTER"),
	KP_FORM14(14,"KP FORM # 14: AGREEMENT FOR ARBITRATION"),
	KP_FORM15(15,"KP FORM # 15: ARBITRATION AWARD"),
	KP_FORM16(16,"KP FORM # 16: AMICABLE SETTLEMENT"),
	KP_FORM17(17,"KP FORM # 17: REPUDIATION"),
	KP_FORM18(18,"KP FORM # 18: NOTICE OF HEARING FOR COMPLAINANT (RE: Failure to Appear)"),
	KP_FORM19(19,"KP FORM # 19: NOTICE OF HEARING FOR RESPONDENT (RE: Failure to Appear)"),
	KP_FORM20(20,"KP FORM # 20: CERTIFICATION TO FILE ACTION (FROM LUPON SECRETARY)"),
	KP_FORM20A(21,"KP FORM # 21: CERTIFICATION TO FILE ACTION (FROM PANGKAT SECRETARY)"),
	KP_FORM20B(22,"KP FORM # 22: CERTIFICATION TO FILE ACTION (FROM PANGKAT SECRETARY)"),
	KP_FORM21(23,"KP FORM # 23: CERTIFICATION TO BAR ACTION"),
	KP_FORM22(24,"KP FORM # 24: CERTIFICATION TO BAR COUNTERCLAIM"),
	KP_FORM23(25,"KP FORM # 25: MOTION FOR EXECUTION"),
	KP_FORM24A(26,"KP FORM # 26: NOTICE OF HEARING (RE: MOTION FOR EXECUTION) - COMPLAINANTS"),
	KP_FORM24B(27,"KP FORM # 26: NOTICE OF HEARING (RE: MOTION FOR EXECUTION) - RESPONDENTS"),
	KP_FORM25(28,"KP FORM # 27: NOTICE OF EXECUTION"),
	KP_FORM26(29,"KP FORM # 28: MONTHLY TRANSMITTAL OF FINAL REPORTS"),
	INVITATION_FORM_WITNESS(30,"INVITATION TO WITNESS"),
	INVITATION_FORM_COMPLAINANT(31,"INVITATION TO COMPLAINANT"),
	INVITATION_FORM_RESPONDENT(32,"INVITATION TO RESPONDENT");
	
	private int id;
	private String name;
	
	public int getId(){
		return id;
	}
	
	public String getName(){
		return name;
	}
	
	private KPForms(int id, String name){
		this.id = id;
		this.name = name;
	}
	
	public static String typeName(int id){
		for(KPForms type : KPForms.values()){
			if(id==type.getId()){
				return type.getName();
			}
		}
		return KPForms.KP_FORM7.getName();
	}
	public static int typeId(String name){
		for(KPForms type : KPForms.values()){
			if(name.equalsIgnoreCase(type.getName())){
				return type.getId();
			}
		}
		return KPForms.KP_FORM7.getId();
	}
	
}
